### ISSUE TITLE
Unable to batch push data on the index

### ISSUE THREAD

**Issue by hualongdai** [algolia/jekyll-algolia#55] opened 2018-03-15 08:58 UTC
Hello,

Just found out about Algolia and its Jekyll plugin.

However, when I run the command:

```
ALGOLIA_API_KEY='secret' bundle exec jekyll algolia --trace
```

I stumble upon the following issue:

```
Processing site...                                                               
Extracting records...                                                            
Updating records in index prod_BLOG_SEARCH...                                    
Records to delete: 0                                                             
Records to add:    276                                                           
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
NoMethodError: undefined method `[]' for nil:NilClass
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll/algolia/error_handler.rb:198:in `record_too_big?'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll/algolia/error_handler.rb:58:in `block in identify'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll/algolia/error_handler.rb:57:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll/algolia/error_handler.rb:57:in `identify'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll/algolia/error_handler.rb:23:in `stop'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll/algolia/indexer.rb:154:in `rescue in block in update_records'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll/algolia/indexer.rb:151:in `block in update_records'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll/algolia/indexer.rb:150:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll/algolia/indexer.rb:150:in `each_slice'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll/algolia/indexer.rb:150:in `update_records'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll/algolia/indexer.rb:192:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll-algolia.rb:119:in `write'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:75:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll-algolia.rb:57:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-algolia-1.1.0/lib/jekyll/commands/algolia.rb:42:in `block (2 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
  /usr/local/bin/jekyll:23:in `load'
  /usr/local/bin/jekyll:23:in `<top (required)>'

```

**Comment by pixelastic** [comment] 2018-03-15 11:42
Hey, thanks for the issue report,

Could you try with the version 1.1.5 of the jekyll-algolia plugin?

If this still fails, you could try with the `--verbose` flag to get more information (it can be **very** verbose). 

If this still fails, would you have a git repo where I could try it myself?

**Comment by hualongdai** [comment] 2018-03-15 11:59
thanks, it work, but there is another proplem

```
 [✗ Error] Record is too big                                                     
                                                                                 
 The jekyll-algolia plugin could not push one of your records as it exceeds      
 the 10 Kb size limit.  
```
is there a config option to solve it

**Comment by pixelastic** [comment] 2018-03-15 12:50
There is no option to increase the maximum size of the record, unfortunately.

This error is often caused by a badly formatted HTML content (like content missing a closing tag, making the parser go crazy and grabbing too much content). Sometimes, it also happens because of other plugins not playing nicely with jekyll-algolia.

The error message should let you know that it created a log file (along with it path), where you can find more details about the specific record that was too big (it should even suggest some of the fields as beeing too big). Could you have a look at this file and see if there is anything obvious you could fix? If not, no worries, you could just paste the content of the error log file here and I'll have a look.

**Comment by hualongdai** [comment] 2018-03-15 12:57
ah...，i fixed it. that is due to my manual excerpt with setting `<!-- more -->` flag

**Comment by pixelastic** [comment] 2018-03-15 13:21
Great, glad you could solve the issue.

I'm going to close it, but don't hesitate to open a new one if you're having any other issues.

:wave:

**Closed by pixelastic** 2018-03-15 13:21 UTC
