### ISSUE TITLE
jekyll 3.8.3 | Error:  undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by mdxprograms** [algolia/jekyll-algolia#90] opened 2018-09-04 16:35 UTC
### What is the current behavior?
When at the `extracting records` phase I receive 
```bash
jekyll 3.8.3 | Error:  undefined method `split' for nil:NilClass
```

### What is your expected behavior?
Should complete successfully

### Git repository to reproduce the issue:
This is a private repo.

### Ruby version used:
2.4.3

### Jekyll version used:
jekyll 3.8.3

**Comment by mdxprograms** [comment] 2018-09-05 20:52
```bash
.rvm/gems/ruby-2.4.3/gems/jekyll-algolia-1.4.7/lib/jekyll/algolia/shrinker.rb:37:in `fit_to_size': undefined method `split' for nil:NilClass (NoMethodError)
```

It seems to be happening on the excerpt sizing. Would this happen if excerpt isn't defined?

**Comment by mdxprograms** [comment] 2018-09-10 17:58
Found the issue if anyone stumbles upon the same problem.
We had to increase the size of both record and batch sizes

```yaml
max_record_size:     20000
indexing_batch_size: 2500
```

**Comment by pixelastic** [comment] 2018-10-16 08:28
I'm going to re-open the issue because I don't understand how those values could have an impact on your initial issue. I'm glad it fixed it though :)

@mdxprograms would you be able to share a link to a github repo where I could clone your jekyll website and experience the issue myself?

**Comment by mdxprograms** [comment] 2018-10-26 04:37
@pixelastic unfortunately, it's a private repo :/
I can give details on versions though if that would help?

**Comment by pixelastic** [comment] 2018-10-30 11:19
Unfortunately I don't think that would help much. From my experience, issues like yours are often caused by a specific mix and match of jekyll plugins creating side-effects impacting the indexing. WIthout the whole picture, it's going to be very hard for me to pinpoint the issue.

Well, too bad then, I'll just have to close the issue for real. I'm still glad you managed to find a workaround, though :)

**Closed by pixelastic** 2018-10-30 11:19 UTC

**Comment by sparanoid** [comment] 2018-11-05 16:16
@pixelastic If you don't mind you can try our repo [here](https://github.com/signcl/openbayes.com), it's mixed with some Jekyll plugins and cannot generate the correct index.
